[package]
name = "method_comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crate-inspector = { git = "https://github.com/rajyan/crate-inspector", branch = "for-wasm-xslxwriter" }
clap = { version = "4.4", features = ["derive"] }
